{
    "An exception of category 'Configuration' occurred while\n   [0] Processing run: 1 lumi: 6 event: 501\n   [1] Running path 'datamixing_step'\n   [2] Calling event method for module DataMixingModule/'mixData'\nException Message:\nRootInputFileSequence::readOneRandom(): no input files specified for secondary input source.\n": [
        "500202.0"
    ],
    "An exception of category 'LogicError' occurred while\n   [0] Processing run: 1\n   [1] Calling global beginRun for module Pythia8HadronizerFilter/'generator'\nException Message:\n::getByToken: An attempt was made to read a Run product before endRun() was called.\nThe index of the token was 1.\n": [
        "513.0",
        "521.0",
        "523.0",
        "519.0",
        "516.0",
        "525.0",
        "528.0"
    ]
}