{
    "An exception of category 'LogicError' occurred while\n   [0] Processing run: 1\n   [1] Calling global beginRun for module Pythia8HadronizerFilter/'generator'\nException Message:\n::getByToken: An attempt was made to read a Run product before endRun() was called.\nThe index of the token was 1.\n": [
        "523.0",
        "521.0",
        "525.0",
        "516.0",
        "528.0",
        "519.0",
        "513.0",
        "529.0",
        "526.0"
    ],
    "An exception of category 'ProductNotFound' occurred while\n   [0] Processing run: 1 lumi: 1 event: 1\n   [1] Running path 'reconstruction_step'\n   [2] Calling event method for module GoodSeedProducer/'trackerDrivenElectronSeedsTmp'\nException Message:\nPrincipal::getByToken: Found zero products matching all criteria\nLooking for type: std::vector<reco::Track>\nLooking for module label: generalTracksBeforeMixing\nLooking for productInstanceName: \n\n   Additional Info:\n      [a] If you wish to continue processing events after a ProductNotFound exception,\nadd \"SkipEvent = cms.untracked.vstring('ProductNotFound')\" to the \"options\" PSet in the configuration.\n\n": [
        "25401.0",
        "401.0",
        "400.0",
        "25400.2",
        "25400.0"
    ]
}